version: 0.2
os: linux
files:
- source: /
  destination: /home/ec2-user/idexport/

permissions:
  - object: /home/ec2-user/idexport/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /home/ec2-user/idexport/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/001-init.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: scripts/002-install-deps.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/003-restart-pm2.sh
      timeout: 180
      runas: ec2-user
